name: Build and Push Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/movie-db-frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/movie-db-frontend:latest